# _self_ = this yaml file configs 
# priority of _self_ is lower than followed configs 
# ex. if data config value is null, use config.yaml's data config
defaults:
  - _self_
  - data : null
  - task: null
  - model: null
  - train : null 

data : 
  train : 'nsmc/ratings_train.txt'
  test : 'nsmc/ratings_test.txt'
  tokenizer :
    type : huggingface
    name : bert-base-multilingual-cased

task : 
  type : classification

train :
  criterion : cross_entropy 
  optimizer : null 
  lr_scheduler : null 
